/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/DreamGlaze.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/DreamGlaze.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.glass2.geometry} material={materials['glass.001']} />
      <mesh geometry={nodes.glass1.geometry} material={materials['glass.001']} />
      <mesh geometry={nodes.Cube011.geometry} material={materials.color2} />
      <mesh geometry={nodes.frame2_p1.geometry} material={materials.color2} />
      <mesh geometry={nodes.frame2_p2.geometry} material={materials.Cashmere} />
      <mesh geometry={nodes.screen_frame_full.geometry} material={materials.White} />
      <mesh geometry={nodes.screen_frame_half.geometry} material={materials.White} />
      <mesh geometry={nodes.screen_glass1_full.geometry} material={materials['glass.001']} />
      <mesh geometry={nodes.screen_glass1_half.geometry} material={materials['glass.001']} />
      <mesh geometry={nodes.AmericanBrown.geometry} material={materials.AmericanBrown} />
      <mesh geometry={nodes.Beige.geometry} material={materials.Beige} />
      <mesh geometry={nodes.Black.geometry} material={materials.Black} />
      <mesh geometry={nodes.Burgundy.geometry} material={materials.Burgundy} />
      <mesh geometry={nodes.Cashmere.geometry} material={materials.Cashmere} />
      <mesh geometry={nodes.Clay.geometry} material={materials.Clay} />
      <mesh geometry={nodes.Cranberry.geometry} material={materials.Cranberry} />
      <mesh geometry={nodes.Ivory.geometry} material={materials.Ivory} />
      <mesh geometry={nodes.OldWorldBlue.geometry} material={materials.OldWorldBlue} />
      <mesh geometry={nodes.Sable.geometry} material={materials.Sable} />
      <mesh geometry={nodes.Sandalwood.geometry} material={materials.Sandalwood} />
      <mesh geometry={nodes.Sandtone.geometry} material={materials.Sandtone} />
      <mesh geometry={nodes.UniversalBrown.geometry} material={materials.UniversalBrown} />
      <mesh geometry={nodes.WedgeWoodBlue.geometry} material={materials.WedgeWoodBlue} />
      <mesh geometry={nodes.Wicker.geometry} material={materials.Wicker} />
      <mesh geometry={nodes.OakWood.geometry} material={materials.OakWood} />
      <mesh geometry={nodes.BrazilianCherryWood.geometry} material={materials.BrazilianCherryWood} />
      <mesh geometry={nodes.ProvincialWood.geometry} material={materials.ProvincialWood} />
      <mesh geometry={nodes.GoldenOak.geometry} material={materials.GoldenOak} />
      <mesh geometry={nodes.White.geometry} material={materials.White} />
      <mesh geometry={nodes.Brown.geometry} material={materials.Brown} />
      <mesh geometry={nodes.Bronze.geometry} material={materials.Bronze} />
      <mesh geometry={nodes.ForestGreen.geometry} material={materials.ForestGreen} />
      <mesh geometry={nodes.window_1.geometry} material={materials.White} />
      <mesh geometry={nodes.window_2.geometry} material={materials.color2} />
      <mesh geometry={nodes.frame1_1.geometry} material={materials.White} />
      <mesh geometry={nodes.frame1_2.geometry} material={materials.color2} />
      <mesh geometry={nodes.frame2_1.geometry} material={materials.White} />
      <mesh geometry={nodes.frame2_2.geometry} material={materials.color2} />
      <mesh geometry={nodes.sdl0_up_1.geometry} material={materials.White} />
      <mesh geometry={nodes.sdl0_up_2.geometry} material={materials.color2} />
      <mesh geometry={nodes.gbg0_up_1.geometry} material={materials.White} />
      <mesh geometry={nodes.gbg0_up_2.geometry} material={materials.color2} />
      <mesh geometry={nodes.gbg0_down_1.geometry} material={materials.White} />
      <mesh geometry={nodes.gbg0_down_2.geometry} material={materials.color2} />
      <mesh geometry={nodes.sdl0_down_1.geometry} material={materials.White} />
      <mesh geometry={nodes.sdl0_down_2.geometry} material={materials.color2} />
      <mesh geometry={nodes.gbg1_down_1.geometry} material={materials.White} />
      <mesh geometry={nodes.gbg1_down_2.geometry} material={materials.color2} />
      <mesh geometry={nodes.gbg1_up_1.geometry} material={materials.White} />
      <mesh geometry={nodes.gbg1_up_2.geometry} material={materials.color2} />
      <mesh geometry={nodes.sdl1_down_1.geometry} material={materials.White} />
      <mesh geometry={nodes.sdl1_down_2.geometry} material={materials.color2} />
      <mesh geometry={nodes.sdl1_up_1.geometry} material={materials.White} />
      <mesh geometry={nodes.sdl1_up_2.geometry} material={materials.color2} />
      <mesh geometry={nodes.gbg2_down_1.geometry} material={materials.White} />
      <mesh geometry={nodes.gbg2_down_2.geometry} material={materials.color2} />
      <mesh geometry={nodes.gbg2_up_1.geometry} material={materials.White} />
      <mesh geometry={nodes.gbg2_up_2.geometry} material={materials.color2} />
      <mesh geometry={nodes.sdl2_down_1.geometry} material={materials.White} />
      <mesh geometry={nodes.sdl2_down_2.geometry} material={materials.color2} />
      <mesh geometry={nodes.sdl2_up_1.geometry} material={materials.White} />
      <mesh geometry={nodes.sdl2_up_2.geometry} material={materials.color2} />
      <mesh geometry={nodes.gbg3_down_1.geometry} material={materials.White} />
      <mesh geometry={nodes.gbg3_down_2.geometry} material={materials.color2} />
      <mesh geometry={nodes.gbg3_up_1.geometry} material={materials.White} />
      <mesh geometry={nodes.gbg3_up_2.geometry} material={materials.color2} />
      <mesh geometry={nodes.sdl3_down_1.geometry} material={materials.White} />
      <mesh geometry={nodes.sdl3_down_2.geometry} material={materials.color2} />
      <mesh geometry={nodes.sdl3_up_1.geometry} material={materials.White} />
      <mesh geometry={nodes.sdl3_up_2.geometry} material={materials.color2} />
      <mesh geometry={nodes.gbg4_down_1.geometry} material={materials.White} />
      <mesh geometry={nodes.gbg4_down_2.geometry} material={materials.color2} />
      <mesh geometry={nodes.gbg4_up_1.geometry} material={materials.White} />
      <mesh geometry={nodes.gbg4_up_2.geometry} material={materials.color2} />
      <mesh geometry={nodes.sdl4_down_1.geometry} material={materials.White} />
      <mesh geometry={nodes.sdl4_down_2.geometry} material={materials.color2} />
      <mesh geometry={nodes.sdl4_up_1.geometry} material={materials.White} />
      <mesh geometry={nodes.sdl4_up_2.geometry} material={materials.color2} />
      <mesh geometry={nodes.gbg5_down_1.geometry} material={materials.White} />
      <mesh geometry={nodes.gbg5_down_2.geometry} material={materials.color2} />
      <mesh geometry={nodes.gbg5_up_1.geometry} material={materials.White} />
      <mesh geometry={nodes.gbg5_up_2.geometry} material={materials.color2} />
      <mesh geometry={nodes.sdl5_down_1.geometry} material={materials.White} />
      <mesh geometry={nodes.sdl5_down_2.geometry} material={materials.color2} />
      <mesh geometry={nodes.sdl5_up_1.geometry} material={materials.White} />
      <mesh geometry={nodes.sdl5_up_2.geometry} material={materials.color2} />
    </group>
  )
}

useGLTF.preload('/DreamGlaze.glb')
