/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Impervia_Casement.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/Impervia_Casement.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="window" position={[0, 0, -0.067]} rotation={[Math.PI, 0, Math.PI]}>
          <mesh name="window_1" geometry={nodes.window_1.geometry} material={materials.White} />
          <mesh name="window_2" geometry={nodes.window_2.geometry} material={materials.Color2} />
        </group>
        <group name="frame1" position={[-0.368, 0, -0.009]} rotation={[Math.PI, 0, Math.PI]}>
          <mesh name="frame1_1" geometry={nodes.frame1_1.geometry} material={materials.White} />
          <mesh name="frame1_2" geometry={nodes.frame1_2.geometry} material={materials.color2} />
        </group>
        <mesh name="bar1" geometry={nodes.bar1.geometry} material={materials.Color2} position={[0, 0, -0.067]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="bar2" geometry={nodes.bar2.geometry} material={materials.Color2} position={[0, 0, -0.067]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="glass1" geometry={nodes.glass1.geometry} material={materials['glass.001']} position={[0, 0, -0.014]} rotation={[Math.PI, 0, Math.PI]} scale={[1, 1, 0.914]} />
        <mesh name="button" geometry={nodes.button.geometry} material={materials.Black} position={[-0.346, -0.566, -0.048]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="frame1001" geometry={nodes.frame1001.geometry} material={materials.Black} position={[-0.09, -0.608, -0.026]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="Bolt" geometry={nodes.Bolt.geometry} material={materials.Black} position={[-0.206, -0.606, -0.023]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.772} />
        <mesh name="frame1002" geometry={nodes.frame1002.geometry} material={materials.Black} position={[-0.145, -0.604, -0.029]} rotation={[-Math.PI, 0.055, -Math.PI]} />
        <mesh name="lock1" geometry={nodes.lock1.geometry} material={materials.Black} position={[0.36, -0.373, -0.063]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="lock2" geometry={nodes.lock2.geometry} material={materials.Black} position={[0.361, -0.354, -0.061]} rotation={[Math.PI, 0, Math.PI]} />
        <mesh name="lock3" geometry={nodes.lock3.geometry} material={materials.Black} position={[0.361, -0.354, -0.061]} rotation={[Math.PI, 0, Math.PI]} />
        <group name="flat0" position={[0, 0, -0.014]} scale={1.049}>
          <mesh name="flat0_1" geometry={nodes.flat0_1.geometry} material={materials['White.002']} />
          <mesh name="flat0_2" geometry={nodes.flat0_2.geometry} material={materials.color2} />
        </group>
        <group name="gbg0" position={[0, 0.001, -0.014]} rotation={[0, 0, -Math.PI / 2]} scale={1.049}>
          <mesh name="gbg0_1" geometry={nodes.gbg0_1.geometry} material={materials['White.002']} />
          <mesh name="gbg0_2" geometry={nodes.gbg0_2.geometry} material={materials.color2} />
        </group>
        <group name="sdl0" position={[0, 0, -0.014]} scale={1.049}>
          <mesh name="sdl0_1" geometry={nodes.sdl0_1.geometry} material={materials['White.002']} />
          <mesh name="sdl0_2" geometry={nodes.sdl0_2.geometry} material={materials.color2} />
        </group>
        <group name="flat1" position={[0, 0, -0.014]} scale={1.049}>
          <mesh name="flat1_1" geometry={nodes.flat1_1.geometry} material={materials['White.002']} />
          <mesh name="flat1_2" geometry={nodes.flat1_2.geometry} material={materials.color2} />
        </group>
        <group name="gbg1" position={[0, 0.001, -0.014]} rotation={[0, 0, -Math.PI / 2]} scale={1.049}>
          <mesh name="gbg1_1" geometry={nodes.gbg1_1.geometry} material={materials['White.002']} />
          <mesh name="gbg1_2" geometry={nodes.gbg1_2.geometry} material={materials.color2} />
        </group>
        <group name="sdl1" position={[0, 0, -0.014]} scale={1.049}>
          <mesh name="sdl1_1" geometry={nodes.sdl1_1.geometry} material={materials['White.002']} />
          <mesh name="sdl1_2" geometry={nodes.sdl1_2.geometry} material={materials.color2} />
        </group>
        <group name="flat2" position={[0, 0, -0.014]} scale={1.049}>
          <mesh name="flat2_1" geometry={nodes.flat2_1.geometry} material={materials['White.002']} />
          <mesh name="flat2_2" geometry={nodes.flat2_2.geometry} material={materials.color2} />
        </group>
        <group name="gbg2" position={[0, 0.001, -0.014]} rotation={[0, 0, -Math.PI / 2]} scale={1.049}>
          <mesh name="gbg2_1" geometry={nodes.gbg2_1.geometry} material={materials['White.002']} />
          <mesh name="gbg2_2" geometry={nodes.gbg2_2.geometry} material={materials.color2} />
        </group>
        <group name="sdl2" position={[0, 0, -0.014]} scale={1.049}>
          <mesh name="sdl2_1" geometry={nodes.sdl2_1.geometry} material={materials['White.002']} />
          <mesh name="sdl2_2" geometry={nodes.sdl2_2.geometry} material={materials.color2} />
        </group>
        <group name="flat3" position={[0, 0, -0.014]} scale={1.049}>
          <mesh name="flat3_1" geometry={nodes.flat3_1.geometry} material={materials['White.002']} />
          <mesh name="flat3_2" geometry={nodes.flat3_2.geometry} material={materials.color2} />
        </group>
        <group name="gbg3" position={[0, 0.001, -0.014]} rotation={[0, 0, -Math.PI / 2]} scale={1.049}>
          <mesh name="gbg3_1" geometry={nodes.gbg3_1.geometry} material={materials['White.002']} />
          <mesh name="gbg3_2" geometry={nodes.gbg3_2.geometry} material={materials.color2} />
        </group>
        <group name="sdl3" position={[0, 0, -0.014]} scale={1.049}>
          <mesh name="sdl3_1" geometry={nodes.sdl3_1.geometry} material={materials['White.002']} />
          <mesh name="sdl3_2" geometry={nodes.sdl3_2.geometry} material={materials.color2} />
        </group>
        <mesh name="Black" geometry={nodes.Black.geometry} material={materials.Black} />
        <mesh name="Brown" geometry={nodes.Brown.geometry} material={materials.Brown} />
        <mesh name="MorningSkyGray" geometry={nodes.MorningSkyGray.geometry} material={materials.MorningSkyGray} />
        <mesh name="Tan" geometry={nodes.Tan.geometry} material={materials.Tan} />
        <mesh name="White" geometry={nodes.White.geometry} material={materials['White.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Impervia_Casement.glb')
